version: "3.7"
services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: permanent
    healthcheck:
      test: pg_isready -d permanent
    ports:
      - "5432:5432"
  stela:
    build: 
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      database:
        condition: service_healthy
