version: "3.7"
services:
  stela:
    build:
      context: ./
      dockerfile: Dockerfile.test
    networks:
      - devenv
    volumes:
      - ../stela:/usr/local/apps/stela
networks:
  devenv:
    name: devenv_default
    external: true
