services:
  stela:
    build:
      context: ./
      dockerfile: packages/api/Dockerfile.test
    networks:
      - devenv
    environment:
      - ENV=test
    volumes:
      - ./coverage:/usr/local/apps/stela/packages/api/coverage
networks:
  devenv:
    name: devenv_default
    external: true
