version: "3.7"
services:
  stela:
    build:
      context: ./
      dockerfile: Dockerfile.test
    networks:
      - devenv
    environment:
      - ENV=test
    volumes:
      - ./coverage:/usr/local/apps/stela/coverage
networks:
  devenv:
    name: devenv_default
    external: true
