export const UnrecognizedExtensionMIMEType = "application/octet-stream";

export const PermanentTypeByFileExtension: Record<string, string> = {
	zip: "type.file.archive.zip",
	"7z": "type.file.archive.7zip",
	aac: "type.file.audio.aac",
	aiff: "type.file.audio.aiff",
	flac: "type.file.audio.flac",
	mp3: "type.file.audio.mp3",
	m4a: "type.file.audio.m4a",
	ogg: "type.file.audio.ogg",
	wav: "type.file.audio.wav",
	wma: "type.file.audio.wma",
	html: "type.file.document.html",
	htm: "type.file.document.htm",
	doc: "type.file.document.doc",
	docx: "type.file.document.docx",
	eml: "type.file.document.eml",
	odt: "type.file.document.odt",
	rtf: "type.file.document.rtf",
	txt: "type.file.document.txt",
	bmp: "type.file.image.bmp",
	gif: "type.file.image.gif",
	jpeg: "type.file.image.jpeg",
	jpg: "type.file.image.jpg",
	png: "type.file.image.png",
	tif: "type.file.image.tif",
	tiff: "type.file.image.tiff",
	heic: "type.file.image.heic",
	heif: "type.file.image.heif",
	pdf: "type.file.pdf.pdf",
	key: "type.file.presentation.key",
	odp: "type.file.presentation.odp",
	pptx: "type.file.presentation.pptx",
	ppt: "type.file.presentation.ppt",
	ged: "type.file.gedcom",
	gdz: "type.file.gedzip",
	csv: "type.file.spreadsheet.csv",
	ods: "type.file.spreadsheet.ods",
	xls: "type.file.spreadsheet.xls",
	xlsx: "type.file.spreadsheet.xlsx",
	avi: "type.file.video.avi",
	mov: "type.file.video.mov",
	mp4: "type.file.video.mp4",
	ogv: "type.file.video.ogv",
	webm: "type.file.video.webm",
	wmv: "type.file.video.wmv",
	"3gp": "type.file.video.3gp",
	"3g2": "type.file.vidoe.3g2",
	m4v: "type.file.video.m4v",
	mkv: "type.file.video.mkv",
	mpg: "type.file.video.mpg",
	mpeg: "type.file.video.mpeg",
};
export const UnrecognizedExtensionPermanentType = "type.file.unknown.null";
