openapi: 3.0.0
info:
  title: Permanent Core API
  version: 1.0.0
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
servers:
  - url: https://api.permanent.org/v2
components:
  securitySchemes:
    bearerHttpAuthentication:
      type: http
      scheme: bearer
      bearerFormat: JWT
    permanentShareToken:
      description: A token provided via a share link, granting read-only access
      type: apiKey
      in: header
      name: X-Permanent-Share-Token
paths:
  /login:
    $ref: "./paths/authentication.yaml#/login"
  /token:
    $ref: "./paths/authentication.yaml#/token"
  /start-mfa:
    $ref: "./paths/authentication.yaml#/start-mfa"
  /complete-mfa:
    $ref: "./paths/authentication.yaml#/complete-mfa"
  /logout:
    $ref: "./paths/authentication.yaml#/logout"
  /mfa-methods:
    $ref: "./paths/mfa_management.yaml#/mfa-method"
  /mfa-methods/{methodId}:
    $ref: "./paths/mfa_management.yaml#/mfa-method-with-id"
  /accounts:
    $ref: "./paths/account.yaml#/account"
  /share-links:
    $ref: "./paths/share_link.yaml#/share-link"
  /share-links/{shareLinkId}:
    $ref: "./paths/share_link.yaml#/share-link-with-id"
  /records:
    $ref: "./paths/record.yaml#/records"
  /records/{id}/share-links:
    $ref: "./paths/record.yaml#/records-id-share-links"
  /folders:
    $ref: "./paths/folder.yaml#/folders"
  /folders/{id}/children:
    $ref: "./paths/folder.yaml#/folders-id-children"
  /folders/{id}/share-links:
    $ref: "./paths/folder.yaml#/folders-id-share-links"
  /archive/{id}/folders/shared:
    $ref: "./paths/archive.yaml#/archive-id-folders-shared"
  /applications:
    $ref: "./paths/application.yaml#/applications"
  /applications/{id}:
    $ref: "./paths/application.yaml#/applications-with-id"
  /developer-accounts:
    $ref: "./paths/developer_account.yaml#/developer-accounts"
  /notifications:
    $ref: "./paths/notification.yaml#/notifications"
