openapi: 3.0.0
info:
  title: Permanent API
  version: 1.0.0
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
servers:
  - url: https://api.permanent.org/v2
components:
  securitySchemes:
    bearerHttpAuthentication:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /feature-flags:
    $ref: "./paths/feature_flags.yaml#/feature-flags"
  /feature-flags/{id}:
    $ref: "./paths/feature_flags.yaml#/feature-flags~1{id}"
  /invite-codes:
    $ref: "./paths/invite_codes.yaml#/invite-codes"
  /invite-codes/{id}:
    $ref: "./paths/invite_codes.yaml#/invite-codes~1{id}"
  /record/{id}:
    $ref: "./paths/records.yaml#/record~1{id}"
  /folder/{id}:
    $ref: "./paths/folders.yaml#/folder~1{id}"
