version: "3.7"
services:
  stela:
    build:
      context: ../..
      dockerfile: packages/api/Dockerfile.test
    networks:
      - devenv
networks:
  devenv:
    name: devenv_default
    external: true
