export enum FileType {
	VideoAvi = "type.file.video.avi",
	VideoMpg = "type.file.video.mpg",
	ImageBmp = "type.file.image.bmp",
	ArchiveZip = "type.file.archive.zip",
	SpreadsheetXls = "type.file.spreadsheet.xls",
	VideoMpeg = "type.file.video.mpeg",
	VideoWmv = "type.file.video.wmv",
	ImageHeic = "type.file.image.heic",
	AudioWma = "type.file.audio.wma",
	Unknown = "type.file.unknown.null",
	VideoMkv = "type.file.video.mkv",
	Gedcom = "type.file.gedcom",
	ImagePng = "type.file.image.png",
	AudioWav = "type.file.audio.wav",
	VideoM4v = "type.file.video.m4v",
	VideoMp4 = "type.file.video.mp4",
	SpreadsheetCsv = "type.file.spreadsheet.csv",
	DocumentHtm = "type.file.document.htm",
	DocumentDocx = "type.file.document.docx",
	PresentationOdp = "type.file.presentation.odp",
	AudioM4a = "type.file.audio.m4a",
	Gedzip = "type.file.gedzip",
	ImageJpg = "type.file.image.jpg",
	ImageTiff = "type.file.image.tiff",
	ImageHeif = "type.file.image.heif",
	AudioMp3 = "type.file.audio.mp3",
	DocumentDoc = "type.file.document.doc",
	SpreadsheetXlsx = "type.file.spreadsheet.xlsx",
	AudioAac = "type.file.audio.aac",
	DocumentEml = "type.file.document.eml",
	VideoWebm = "type.file.video.webm",
	DocumentOdt = "type.file.document.odt",
	ImageGif = "type.file.image.gif",
	ImageJpeg = "type.file.image.jpeg",
	AudioOgg = "type.file.audio.ogg",
	VideoOgv = "type.file.video.ogv",
	ImageTif = "type.file.image.tif",
	AudioFlac = "type.file.audio.flac",
	DocumentTxt = "type.file.document.txt",
	DocumentHtml = "type.file.document.html",
	PresentationKey = "type.file.presentation.key",
	Archive7zip = "type.file.archive.7zip",
	Video3gp = "type.file.video.3gp",
	PresentationPpt = "type.file.presentation.ppt",
	PdfPdfa = "type.file.pdf.pdfa",
	PresentationPptx = "type.file.presentation.pptx",
	SpreadsheetOds = "type.file.spreadsheet.ods",
	AudioAiff = "type.file.audio.aiff",
	VideoMov = "type.file.video.mov",
	DocumentRtf = "type.file.document.rtf",
	PdfPdf = "type.file.pdf.pdf",
}

enum FileExtension {
	Avi = "avi",
	Mpg = "mpg",
	Bmp = "bmp",
	Zip = "zip",
	Xls = "xls",
	Mpeg = "mpeg",
	Wmv = "wmv",
	Heic = "heic",
	Wma = "wma",
	None = "",
	Mkv = "mkv",
	Gedcom = "gedcom",
	Png = "png",
	Wav = "wav",
	M4v = "m4v",
	Mp4 = "mp4",
	Csv = "csv",
	Htm = "htm",
	Docx = "docx",
	Odp = "odp",
	M4a = "m4a",
	Gedzip = "gedzip",
	Jpg = "jpg",
	Tiff = "tiff",
	Heif = "heif",
	Mp3 = "mp3",
	Doc = "doc",
	Xlsx = "xlsx",
	Aac = "aac",
	Eml = "eml",
	Webm = "webm",
	Odt = "odt",
	Gif = "gif",
	Jpeg = "jpeg",
	Ogg = "ogg",
	Ogv = "ogv",
	Tif = "tif",
	Flac = "flac",
	Txt = "txt",
	Html = "html",
	Key = "key",
	SevenZip = "7zip",
	ThreeGp = "3gp",
	Ppt = "ppt",
	Pdfa = "pdfa",
	Pptx = "pptx",
	Ods = "ods",
	Aiff = "aiff",
	Mov = "mov",
	Rtf = "rtf",
	Pdf = "pdf",
}

const FileTypeToFileExtension: Record<FileType, FileExtension> = {
	[FileType.VideoAvi]: FileExtension.Avi,
	[FileType.VideoMpg]: FileExtension.Mpg,
	[FileType.ImageBmp]: FileExtension.Bmp,
	[FileType.ArchiveZip]: FileExtension.Zip,
	[FileType.SpreadsheetXls]: FileExtension.Xls,
	[FileType.VideoMpeg]: FileExtension.Mpeg,
	[FileType.VideoWmv]: FileExtension.Wmv,
	[FileType.ImageHeic]: FileExtension.Heic,
	[FileType.AudioWma]: FileExtension.Wma,
	[FileType.Unknown]: FileExtension.None,
	[FileType.VideoMkv]: FileExtension.Mkv,
	[FileType.Gedcom]: FileExtension.Gedcom,
	[FileType.ImagePng]: FileExtension.Png,
	[FileType.AudioWav]: FileExtension.Wav,
	[FileType.VideoM4v]: FileExtension.M4v,
	[FileType.VideoMp4]: FileExtension.Mp4,
	[FileType.SpreadsheetCsv]: FileExtension.Csv,
	[FileType.DocumentHtm]: FileExtension.Htm,
	[FileType.DocumentDocx]: FileExtension.Docx,
	[FileType.PresentationOdp]: FileExtension.Odp,
	[FileType.AudioM4a]: FileExtension.M4a,
	[FileType.Gedzip]: FileExtension.Gedzip,
	[FileType.ImageJpg]: FileExtension.Jpg,
	[FileType.ImageTiff]: FileExtension.Tiff,
	[FileType.ImageHeif]: FileExtension.Heif,
	[FileType.AudioMp3]: FileExtension.Mp3,
	[FileType.DocumentDoc]: FileExtension.Doc,
	[FileType.SpreadsheetXlsx]: FileExtension.Xlsx,
	[FileType.AudioAac]: FileExtension.Aac,
	[FileType.DocumentEml]: FileExtension.Eml,
	[FileType.VideoWebm]: FileExtension.Webm,
	[FileType.DocumentOdt]: FileExtension.Odt,
	[FileType.ImageGif]: FileExtension.Gif,
	[FileType.ImageJpeg]: FileExtension.Jpeg,
	[FileType.AudioOgg]: FileExtension.Ogg,
	[FileType.VideoOgv]: FileExtension.Ogv,
	[FileType.ImageTif]: FileExtension.Tif,
	[FileType.AudioFlac]: FileExtension.Flac,
	[FileType.DocumentTxt]: FileExtension.Txt,
	[FileType.DocumentHtml]: FileExtension.Html,
	[FileType.PresentationKey]: FileExtension.Key,
	[FileType.Archive7zip]: FileExtension.SevenZip,
	[FileType.Video3gp]: FileExtension.ThreeGp,
	[FileType.PresentationPpt]: FileExtension.Ppt,
	[FileType.PdfPdfa]: FileExtension.Pdfa,
	[FileType.PresentationPptx]: FileExtension.Pptx,
	[FileType.SpreadsheetOds]: FileExtension.Ods,
	[FileType.AudioAiff]: FileExtension.Aiff,
	[FileType.VideoMov]: FileExtension.Mov,
	[FileType.DocumentRtf]: FileExtension.Rtf,
	[FileType.PdfPdf]: FileExtension.Pdf,
};

export const getFileExtensionByFileType = (type: FileType): FileExtension =>
	FileTypeToFileExtension[type];
