import { config } from "dotenv";
import { requireEnv } from "require-env-variable";

config({ path: "../../.env" });

export const {
	ARCHIVEMATICA_HOST_URL,
	ARCHIVEMATICA_API_KEY,
	ARCHIVEMATICA_ORIGINAL_LOCATION_ID,
	ARCHIVEMATICA_PROCESSING_WORKFLOW,
} = requireEnv(
	"ARCHIVEMATICA_HOST_URL",
	"ARCHIVEMATICA_API_KEY",
	"ARCHIVEMATICA_ORIGINAL_LOCATION_ID",
	"ARCHIVEMATICA_PROCESSING_WORKFLOW",
);
