applicationScope:
  type: string
  enum:
    - record.create
    - folder.view
    - folder.create
    - archive.view
    - archive.create
    - storage.view

application:
  type: object
  required: [id, secret, scopes, redirectUris]
  properties:
    id:
      type: string
    secret:
      type: string
    scopes:
      type: array
      items:
        type: string
    redirectUris:
      type: array
      items:
        type: string
        format: uri
