FROM node:18-alpine
WORKDIR /usr/local/apps/stela/

RUN apk add curl \
    postgresql-client 

COPY package.json .
COPY apps/api/package.json apps/api/
RUN npm install -g npm@8.19.3
RUN npm cache clean --force
RUN npm install
RUN npm install --dev
ENV PATH=/usr/local/apps/stela/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/stela/

COPY tsconfig.json ./
COPY apps/api/tsconfig.json ./apps/api
COPY apps/api/src ./apps/api/src

EXPOSE 8080

CMD bash
