name: Validate Terraform (prod)
on:
  push:
    paths:
      - ./terraform/prod_cluster/**
jobs:
  validate_terraform:
    name: "Validate Terraform"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./terraform/prod_cluster
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
