name: Test and Build
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    run_tests:
        uses: ./.github/workflows/test.yml
    build:
        needs:
            - run_tests
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Generate Image Tag
              run: echo "IMAGE_TAG=364159549467.dkr.ecr.$AWS_REGION.amazonaws.com/stela:$([[ ${GITHUB_REF##*/} = main ]] && echo main || echo feature)-$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
              env:
                  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            - name: Build Image
              run: docker build -t $IMAGE_TAG .
            - name: AWS Login
              run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 364159549467.dkr.ecr.$AWS_REGION.amazonaws.com
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: Publish Image to ECR
              run: docker push $IMAGE_TAG
